name = "hanzilianxiqi"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-10-30"
main = "workers-site/index.js"

[site]
bucket = "./build"
entry-point = "workers-site"

[build]
command = "npm run build"

[env.production]
workers_dev = false 